// Patches the AppDelegate that `expo prebuild` generates, so the Twilio voice module and its
// PushKit registry are built during NATIVE launch instead of after the JS bundle has booted. The
// why -- including why the delegate method is added with the Objective-C runtime rather than
// written in Swift -- is in TwilioEarlyInit.swift; this file is only the mechanics.
const fs = require("fs");
const path = require("path");
const { withAppDelegate } = require("expo/config-plugins");

const SWIFT_SOURCE = path.join(__dirname, "TwilioEarlyInit.swift");

// TwilioEarlyInit.swift is a template split on these markers: what follows the first is one line
// for `didFinishLaunchingWithOptions`, what follows the second is the helper class. Anything before
// the first marker documents that file and is dropped.
const LAUNCH_CALL_MARKER = "// tcb:launch-call";
const FILE_SCOPE_MARKER = "// tcb:file-scope";

// Substituted with whatever the generated file names its delegate variable.
const DELEGATE_TOKEN = /__TCB_DELEGATE__/g;

// The React host is built by `startReactNative`, and the delegate is constructed one line above it.
// Installing between the two is what makes the method exist before React Native ever asks for it.
const FACTORY_LINE = /^([ \t]*)(?:let|var)\s+\w+\s*=\s*ExpoReactNativeFactory\(delegate:\s*([A-Za-z_]\w*)\s*\)/m;

// class_addMethod, imp_implementationWithBlock and object_getClass live in the ObjectiveC module.
// Foundation re-exports it on Darwin, but the template never imports Foundation by name either, so
// this is stated rather than assumed.
const RUNTIME_IMPORT = "import ObjectiveC";
const LAST_IMPORT = /^import [^\n]+$(?![\s\S]*^import )/m;

// Prebuild runs repeatedly over an existing ios/ tree, so every injection is REPLACED rather than
// skipped: a marker that only guarded against duplicates would pin whatever was injected first, and
// you would edit the Swift, re-run prebuild, and build the stale copy believing it was the new one.
const BEGIN = ">>> tcb:twilio-early-init (generated by mobile/plugins/withTwilioEarlyInit.js)";
const END = "<<< tcb:twilio-early-init";

function escapeRegExp(literal) {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function block(body) {
  return `// ${BEGIN}\n${body}\n// ${END}`;
}

function stripInjected(contents) {
  return contents
    .replace(
      new RegExp(`\\n*[ \\t]*// ${escapeRegExp(BEGIN)}[\\s\\S]*?// ${escapeRegExp(END)}\\n*`, "g"),
      "\n"
    )
    .replace(new RegExp(`^${escapeRegExp(RUNTIME_IMPORT)}\\n`, "m"), "");
}

/**
 * @param {string} contents  the generated AppDelegate.swift
 * @param {string} swift     the contents of TwilioEarlyInit.swift
 * @returns {string}
 */
function injectTwilioEarlyInit(contents, swift) {
  const callAt = swift.indexOf(LAUNCH_CALL_MARKER);
  const scopeAt = swift.indexOf(FILE_SCOPE_MARKER);
  if (callAt === -1 || scopeAt === -1 || scopeAt < callAt) {
    throw new Error(
      `withTwilioEarlyInit: TwilioEarlyInit.swift needs \`${LAUNCH_CALL_MARKER}\` and then ` +
        `\`${FILE_SCOPE_MARKER}\`, so it can be split into the launch call and the helper class. ` +
        "Put the markers back."
    );
  }
  const launchCall = swift.slice(callAt + LAUNCH_CALL_MARKER.length, scopeAt).replace(/^\n+|\s+$/g, "");
  const helper = swift.slice(scopeAt + FILE_SCOPE_MARKER.length).trim();

  let out = stripInjected(contents);

  const factory = out.match(FACTORY_LINE);
  if (!factory) {
    throw new Error(
      "withTwilioEarlyInit: no `let <name> = ExpoReactNativeFactory(delegate: <delegate>)` in " +
        "AppDelegate.swift. The Expo template changed shape; update " +
        "mobile/plugins/withTwilioEarlyInit.js to match it. Without this the app takes no incoming " +
        "calls on a cold launch (see TwilioEarlyInit.swift)."
    );
  }

  const lastImport = out.match(LAST_IMPORT);
  if (!lastImport) {
    throw new Error("withTwilioEarlyInit: AppDelegate.swift has no import to anchor to.");
  }
  const importEnd = lastImport.index + lastImport[0].length;
  out = `${out.slice(0, importEnd)}\n${RUNTIME_IMPORT}${out.slice(importEnd)}`;

  // Re-match: the import shifted every offset after it.
  const shifted = out.match(FACTORY_LINE);
  const call = launchCall.replace(DELEGATE_TOKEN, shifted[2]);
  out = `${out.slice(0, shifted.index)}${block(call)}\n${out.slice(shifted.index)}`;

  return `${out.trimEnd()}\n\n${block(helper)}\n`;
}

/** @type {import("expo/config-plugins").ConfigPlugin} */
const withTwilioEarlyInit = (config) =>
  withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `withTwilioEarlyInit: expected a Swift AppDelegate, got ${config.modResults.language}.`
      );
    }
    config.modResults.contents = injectTwilioEarlyInit(
      config.modResults.contents,
      fs.readFileSync(SWIFT_SOURCE, "utf8")
    );
    return config;
  });

module.exports = withTwilioEarlyInit;
module.exports.injectTwilioEarlyInit = injectTwilioEarlyInit;
module.exports.SWIFT_SOURCE = SWIFT_SOURCE;
