// Appends TwilioEarlyInit.swift to the AppDelegate that `expo prebuild` generates, so the
// Twilio voice module and its PushKit registry are built during NATIVE launch instead of
// after the JS bundle has booted. The why is in TwilioEarlyInit.swift; this file is only the
// mechanics of getting it there.
//
// It is appended to AppDelegate.swift rather than shipped as a local Expo module because the
// code has to extend the app's OWN React Native delegate class: React Native only asks a
// delegate for pre-built modules if that delegate responds to `extraModulesForBridge:`, and
// an extension in another module would need that class to be extendable across module
// boundaries. Same file, same module, no doubt.
const fs = require("fs");
const path = require("path");
const { withAppDelegate } = require("expo/config-plugins");

const SWIFT_SOURCE = path.join(__dirname, "TwilioEarlyInit.swift");

// The token TwilioEarlyInit.swift is written against. Expo names this class
// `ReactNativeDelegate` in the SDK 54 template; it is rewritten to whatever the generated
// file actually calls it, so a template rename fails loudly at prebuild rather than compiling
// into an extension of a class nothing uses.
const DELEGATE_TOKEN = /\bReactNativeDelegate\b/g;
const DELEGATE_DECLARATION = /class\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*ExpoReactNativeFactoryDelegate\b/;

// Prebuild runs repeatedly over an existing ios/ tree, so the injection has to be REPLACED
// rather than skipped: a marker that only guards against a duplicate would pin whatever Swift
// was injected the first time, and you would edit TwilioEarlyInit.swift, re-run prebuild, and
// read and build the stale copy believing it was the new one.
const BEGIN = "// >>> tcb:twilio-early-init (generated by mobile/plugins/withTwilioEarlyInit.js)";
const END = "// <<< tcb:twilio-early-init";
const INJECTED_BLOCK = new RegExp(`\\n*${escapeRegExp(BEGIN)}[\\s\\S]*?${escapeRegExp(END)}\\n*`, "g");

function escapeRegExp(literal) {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * @param {string} contents  the generated AppDelegate.swift
 * @param {string} swift     the contents of TwilioEarlyInit.swift
 * @returns {string}
 */
function injectTwilioEarlyInit(contents, swift) {
  const original = contents.replace(INJECTED_BLOCK, "\n");

  const match = original.match(DELEGATE_DECLARATION);
  if (!match) {
    throw new Error(
      "withTwilioEarlyInit: no `class <Name>: ExpoReactNativeFactoryDelegate` in AppDelegate.swift. " +
        "The Expo template changed shape; update mobile/plugins/withTwilioEarlyInit.js to match it. " +
        "Without this the app takes no incoming calls on a cold launch (see TwilioEarlyInit.swift)."
    );
  }

  const block = `${BEGIN}\n${swift.replace(DELEGATE_TOKEN, match[1]).trim()}\n${END}`;
  return `${original.trimEnd()}\n\n${block}\n`;
}

/** @type {import("expo/config-plugins").ConfigPlugin} */
const withTwilioEarlyInit = (config) =>
  withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `withTwilioEarlyInit: expected a Swift AppDelegate, got ${config.modResults.language}.`
      );
    }
    config.modResults.contents = injectTwilioEarlyInit(
      config.modResults.contents,
      fs.readFileSync(SWIFT_SOURCE, "utf8")
    );
    return config;
  });

module.exports = withTwilioEarlyInit;
module.exports.injectTwilioEarlyInit = injectTwilioEarlyInit;
module.exports.SWIFT_SOURCE = SWIFT_SOURCE;
