// Patches the AppDelegate that `expo prebuild` generates, so the Twilio voice module and its
// PushKit registry are built during NATIVE launch instead of after the JS bundle has booted. The
// why is in TwilioEarlyInit.swift; this file is only the mechanics of getting it there.
//
// It patches AppDelegate.swift rather than shipping a local Expo module because the code has to
// live on the app's OWN React Native delegate class -- React Native only asks a delegate for
// pre-built modules if that delegate responds to `extraModulesForBridge:`, and the method is an
// `override`, which Swift permits in a class body and nowhere else. So this splits the Swift in
// two: the method goes INSIDE the delegate class, the helper class after it at file scope.
const fs = require("fs");
const path = require("path");
const { withAppDelegate } = require("expo/config-plugins");

const SWIFT_SOURCE = path.join(__dirname, "TwilioEarlyInit.swift");

// TwilioEarlyInit.swift is a template split on these two markers: what follows the first goes
// inside the delegate class (an `override` is legal nowhere else), what follows the second goes
// after it at file scope. Anything before the first marker documents that file and is dropped.
const CLASS_BODY_MARKER = "// tcb:class-body";
const FILE_SCOPE_MARKER = "// tcb:file-scope";

const DELEGATE_DECLARATION = /class\s+[A-Za-z_][A-Za-z0-9_]*\s*:\s*ExpoReactNativeFactoryDelegate\b[^{]*\{/;

// Prebuild runs repeatedly over an existing ios/ tree, so both injections have to be REPLACED
// rather than skipped: a marker that only guards against a duplicate would pin whatever Swift was
// injected the first time, and you would edit TwilioEarlyInit.swift, re-run prebuild, and read and
// build the stale copy believing it was the new one.
const MARKS = {
  method: {
    begin: "  // >>> tcb:twilio-early-init (generated by mobile/plugins/withTwilioEarlyInit.js)",
    end: "  // <<< tcb:twilio-early-init",
  },
  helper: {
    begin: "// >>> tcb:twilio-early-init (generated by mobile/plugins/withTwilioEarlyInit.js)",
    end: "// <<< tcb:twilio-early-init",
  },
};

function escapeRegExp(literal) {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function stripInjected(contents) {
  return contents.replace(
    new RegExp(`\\n*[ \\t]*${escapeRegExp(MARKS.helper.begin)}[\\s\\S]*?${escapeRegExp(MARKS.helper.end)}\\n*`, "g"),
    "\n"
  );
}

/**
 * @param {string} contents  the generated AppDelegate.swift
 * @param {string} swift     the contents of TwilioEarlyInit.swift
 * @returns {string}
 */
function injectTwilioEarlyInit(contents, swift) {
  const bodyAt = swift.indexOf(CLASS_BODY_MARKER);
  const scopeAt = swift.indexOf(FILE_SCOPE_MARKER);
  if (bodyAt === -1 || scopeAt === -1 || scopeAt < bodyAt) {
    throw new Error(
      `withTwilioEarlyInit: TwilioEarlyInit.swift needs \`${CLASS_BODY_MARKER}\` and then ` +
        `\`${FILE_SCOPE_MARKER}\`, so it can be split into the delegate method and the file-scope ` +
        "class. Put the markers back."
    );
  }
  const method = swift.slice(bodyAt + CLASS_BODY_MARKER.length, scopeAt).trimEnd();
  const helper = swift.slice(scopeAt + FILE_SCOPE_MARKER.length).trim();

  const original = stripInjected(contents);
  const declaration = original.match(DELEGATE_DECLARATION);
  if (!declaration) {
    throw new Error(
      "withTwilioEarlyInit: no `class <Name>: ExpoReactNativeFactoryDelegate { ... }` in AppDelegate.swift. " +
        "The Expo template changed shape; update mobile/plugins/withTwilioEarlyInit.js to match it. " +
        "Without this the app takes no incoming calls on a cold launch (see TwilioEarlyInit.swift)."
    );
  }

  // Inside the class body: an override cannot live in an extension.
  const classBodyStart = declaration.index + declaration[0].length;
  const withMethod =
    original.slice(0, classBodyStart) +
    `\n${MARKS.method.begin}\n${method}\n${MARKS.method.end}\n` +
    original.slice(classBodyStart);

  // After it, at file scope.
  return `${withMethod.trimEnd()}\n\n${MARKS.helper.begin}\n${helper}\n${MARKS.helper.end}\n`;
}

/** @type {import("expo/config-plugins").ConfigPlugin} */
const withTwilioEarlyInit = (config) =>
  withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `withTwilioEarlyInit: expected a Swift AppDelegate, got ${config.modResults.language}.`
      );
    }
    config.modResults.contents = injectTwilioEarlyInit(
      config.modResults.contents,
      fs.readFileSync(SWIFT_SOURCE, "utf8")
    );
    return config;
  });

module.exports = withTwilioEarlyInit;
module.exports.injectTwilioEarlyInit = injectTwilioEarlyInit;
module.exports.SWIFT_SOURCE = SWIFT_SOURCE;
